version: '3'

services:
  app:
    image: ${BUILD_IMAGE_TAG}
    build:
      context: .
    restart: unless-stopped
    ports:
      - "8083"
    environment:
      SPRING_PROFILES_ACTIVE: ${TARGET_ENV}

  app_it:
    build:
      context: integration-test
    command: run -r cli app-test.json

networks:
  default:
    driver: bridge