version: '3'

services:
  app:
#    image: ${BRANCH_IMAGE_TAG}
    build:
      context: .
    restart: unless-stopped
    networks:
      - default
    ports:
      - "8080:8080"

networks:
  default:
    driver: bridge