version: '3'

services:
  Spring-starter:
    image: ${BRANCH_IMAGE_TAG}
    restart: unless-stopped
    netorks:
      - default
    ports:
      - "8080:8083"
    environment:
      SPRING_PROFILES_ACTIVE: ${TARGET_ENV}


networks:
  default:
    driver: bridge